# 3세대
SELECT ID
FROM ECOLI_DATA 
WHERE PARENT_ID IN (SELECT ID AS TWO_ID
FROM ECOLI_DATA 
WHERE PARENT_ID IN (
    SELECT ID AS ONE_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL))
ORDER BY ID ASC