SELECT e.ID, 
    CASE WHEN p.CNT_P IS NOT NULL
        THEN p.CNT_P
        ELSE 0
    END AS CHILD_COUNT
FROM ECOLI_DATA AS e
LEFT JOIN (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT_P
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID) AS p
ON e.ID = p.PARENT_ID
ORDER BY e.ID ASC
