-- 코드를 입력하세요
SELECT o.PRODUCT_CODE, SALES_SUM * PRICE AS SALES
FROM PRODUCT  AS o
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_SUM
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) AS s
ON o.PRODUCT_ID = s.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC