-- 코드를 입력하세요
SELECT cf.CAR_ID, cf.CAR_TYPE, cf.FEE
FROM (SELECT c.CAR_ID, c.CAR_TYPE, ROUND(daily_fee * (1 - (DISCOUNT_RATE / 100))) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p
ON p.CAR_TYPE = c.CAR_TYPE
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
AND duration_type = '30일 이상') AS cf
WHERE (cf.FEE >= 500000 AND cf.FEE < 2000000)
AND cf.CAR_ID NOT IN (SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'))
ORDER BY cf.FEE DESC, cf.CAR_TYPE ASC, cf.CAR_ID DESC

# car_type

# history에서 대여 가능 CAR_ID
# (SELECT DISTINCT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE START_DATE < '2022-12-01' OR END_DATE > '2022-10-31')

