WITH cte AS (
  SELECT ID, SIZE_OF_COLONY,
         NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENTILE
  FROM ECOLI_DATA
)
SELECT ID,
       CASE PERCENTILE
         WHEN 1 THEN 'CRITICAL'
         WHEN 2 THEN 'HIGH'
         WHEN 3 THEN 'MEDIUM'
         ELSE 'LOW'
       END AS COLONY_NAME
FROM cte
ORDER BY ID;

# SELECT ID, SIZE_OF_COLONY,
#          NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENTILE
#   FROM ECOLI_DATA