SELECT e.id AS ID,
    CASE 
        WHEN (COLONY_RANK / cnt) <= 0.25
            THEN 'CRITICAL'
        WHEN (COLONY_RANK / cnt) <= 0.5
            THEN 'HIGH'
        WHEN (COLONY_RANK / cnt) <= 0.75
            THEN 'MEDIUM'
        ELSE
            'LOW'
        END AS COLONY_NAME
FROM ECOLI_DATA AS e JOIN (
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK, (SELECT COUNT(*) AS cnt FROM ECOLI_DATA) AS cnt
    FROM ECOLI_DATA) AS r
ON e.id = r.id
ORDER BY e.id ASC

# SELECT ID, SIZE_OF_COLONY,
#          NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENTILE
#   FROM ECOLI_DATA