-- 코드를 입력하세요
SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, (fp.PRICE * SUM(fo.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS fp JOIN (SELECT * FROM FOOD_ORDER WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05') AS fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID ASC;