# SELECT f.FLAVOR
# FROM (
  
# ) f
# ORDER BY TOTAL_ORDER DESC
# LIMIT 3;

SELECT fh.FLAVOR
FROM FIRST_HALF AS fh 
JOIN (SELECT j.FLAVOR, SUM(j.TOTAL_ORDER) AS JULY_TOTAL_ORDER
 FROM JULY AS j 
 GROUP BY j.FLAVOR) AS jt 
ON fh.FLAVOR = jt.FLAVOR
ORDER BY (jt.JULY_TOTAL_ORDER + fh.TOTAL_ORDER) DESC
LIMIT 3;

