-- 코드를 작성해주세요
SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS AS d
CROSS JOIN
(SELECT CODE AS FRONT_CODE
FROM SKILLCODES 
WHERE CATEGORY = 'Front End') AS f
WHERE d.SKILL_CODE & f.FRONT_CODE > 0
ORDER BY d.ID ASC
