-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, o.TOTAL_SALES
FROM USED_GOODS_USER u JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID) AS o
ON u.USER_ID = o.WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
    

