-- 코드를 작성해주세요
SELECT ey.YEAR, (MAX_SIZE - ed.SIZE_OF_COLONY) AS YEAR_DEV, ed.ID
FROM ECOLI_DATA AS ed
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR) AS ey
ON YEAR(ed.DIFFERENTIATION_DATE) = ey.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC