# -- 코드를 작성해주세요
SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fni
ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH IN (SELECT MAX(LENGTH) AS LENGTH FROM FISH_INFO WHERE FISH_TYPE = fi.FISH_TYPE GROUP BY FISH_TYPE)
ORDER BY fi.ID ASC


