-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS ugf
WHERE ugf.BOARD_ID IN (SELECT BOARD_ID
FROM USED_GOODS_BOARD
WHERE VIEWS IN (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD))
ORDER BY ugf.FILE_ID DESC