-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS b 
JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
) AS bs
ON b.BOOK_ID = bs.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC